import Image from 'next/image';
import { Header } from '@/components/Header';
import { Logo } from '@/components/Logo';
import { DiamondMarker } from '@/components/Diamond';
import { StayShowcase } from '@/components/StayShowcase';
import { differentials, hotel, images, imageAlts, journey } from '@/data/hotel';

const services = ['Recepção 24h','Wi-Fi','Estacionamento','Restaurante / jantar','Quartos familiares','Serviço de quarto','Ar-condicionado'];
const reviews = ['“Infraestrutura excelente e atendimento de todos.”','“Café da manhã incrível.”','“Você se sente mais que em casa.”','“Funcionários extremamente solícitos e cuidadosos.”','“Hotel muito confortável.”','“Lençóis e toalhas super macios e limpos.”'];

function Eyebrow({n,children}:{n:string,children:React.ReactNode}){return <p className="eyebrow"><span>{n}</span><DiamondMarker/>{children}</p>}
function Img({src,alt,className='',priority=false}:{src:string,alt:string,className?:string,priority?:boolean}){return <Image className={className} src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 60vw" priority={priority}/>}

export default function Home(){return <main>
  <section className="hero" id="inicio"><Header/><div className="hero-photo"><Img src={images.facade} alt="Fachada do Diamante Rosa Palace Hotel" priority/></div><div className="hero-facet"/><div className="hero-copy"><Eyebrow n="01">COROMANDEL — MINAS GERAIS</Eyebrow><h1>Uma estadia feita de <em>bons detalhes.</em></h1><p>Conforto, cuidado e hospitalidade no coração de Coromandel.</p><div className="actions"><a className="button button--coral" href="#experiencia">Conhecer o hotel <span>→</span></a><a className="button button--line" href={hotel.whatsapp}>Reservar pelo WhatsApp</a></div><div className="hero-proof"><strong>4,6</strong><span className="stars">★★★★★</span><small>Mais de 700 avaliações no Google</small><q>Você se sente mais que em casa.</q></div></div><div className="scroll-note">DESCUBRA <span>↓</span></div></section>

  <section className="experience section" id="experiencia"><div className="section-intro"><Eyebrow n="02">A EXPERIÊNCIA</Eyebrow><h2>O que faz uma estadia ser lembrada?</h2><p>Mais do que um lugar para dormir, é o cuidado presente em cada momento.</p></div><div className="experience-mosaic">{differentials.map(([n,title,text,key],i)=><article className={`difference d${i+1}`} key={n}><div className="difference-img"><Img src={images[key]} alt={imageAlts[key]}/></div><div><span>{n}</span><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

  <section className="stays section section--dark" id="acomodacoes"><div className="stays-title"><Eyebrow n="03">QUARTOS &amp; EXPERIÊNCIAS</Eyebrow><h2>Escolha o seu jeito de estar.</h2><p>Do descanso aos encontros, ambientes bem cuidados para cada momento da sua passagem por Coromandel.</p></div><StayShowcase/></section>

  <section className="journey section"><div className="journey-heading"><Eyebrow n="04">O RITUAL DA ESTADIA</Eyebrow><h2>Do check-in ao café da manhã.</h2><p>Uma experiência completa, com cuidado em cada etapa.</p></div><div className="journey-steps">{journey.map(([,title,text,key])=><article key={title}><span className="journey-marker"><DiamondMarker/></span><h3>{title}</h3><div className="journey-img"><Img src={images[key]} alt={imageAlts[key]}/></div><p>{text}</p></article>)}<div className="journey-line"/></div></section>

  <section className="breakfast"><div className="breakfast-photo"><Img src={images.breakfast} alt="Buffet de café da manhã do Diamante Rosa Palace Hotel"/></div><div className="breakfast-copy"><Eyebrow n="05">CAFÉ DA MANHÃ</Eyebrow><h2>Tem manhã que começa diferente.</h2><p>Um café da manhã farto, preparado e servido com muito cuidado pela nossa equipe.</p><div className="food-list"><span>Frutas</span><span>Bebidas</span><span>Pães</span><span>Bolos</span><span>Opções quentes</span><span>Variedade</span></div></div></section>

  <section className="reviews section"><Eyebrow n="06">AVALIAÇÕES</Eyebrow><div className="review-cloud"><div className="score"><p>Quem passa por aqui percebe.</p><strong>4,6</strong><span>★★★★★</span><small>Mais de 700 avaliações no Google</small><a className="button button--coral" href="#contato">Ver avaliações <b>→</b></a></div>{reviews.map((r,i)=><blockquote key={r} className={`quote q${i+1}`}>{r}<span>★★★★★</span></blockquote>)}</div></section>

  <section className="services section" id="estrutura"><div className="services-copy"><Eyebrow n="07">ESTRUTURA E SERVIÇOS</Eyebrow><h2>Mais do que uma hospedagem.</h2><p>Tudo o que você precisa, em um só lugar — com praticidade e cuidado.</p><div className="service-list">{services.map(s=><span key={s}>{s}</span>)}</div></div><div className="auditorium"><Img src={images.auditorium} alt="Auditório do Diamante Rosa Palace Hotel preparado para eventos"/><div><DiamondMarker/><span>DESTAQUE</span><h3>Auditório para eventos</h3><p>Reuniões, treinamentos e encontros corporativos.</p></div></div></section>

  <section className="location section" id="localizacao"><div className="location-copy"><Eyebrow n="08">LOCALIZAÇÃO</Eyebrow><h2>Coromandel à sua volta.</h2><address>Rua Duque de Caxias, 930<br/>Mangabeiras<br/>Coromandel — MG</address><a href={hotel.maps} target="_blank" rel="noreferrer" className="button button--coral">Abrir no Google Maps <span>↗</span></a></div><div className="map" aria-label="Mapa ilustrativo da localização"><svg viewBox="0 0 800 400" aria-hidden="true"><path d="M0 70 C180 180 300 20 480 120S700 310 800 190M-20 320C190 190 280 370 470 245S690 80 830 120M130 0c45 120-40 240 20 400M590 0c-70 100 40 230-30 400"/><path className="map-water" d="M330 310c80-75 220-90 330-30l140 120H290z"/><g transform="translate(500 155)"><path className="pin" d="M0-48c-27 0-48 21-48 48 0 37 48 82 48 82S48 37 48 0C48-27 27-48 0-48z"/><circle r="13"/></g></svg><span className="map-label">Diamante Rosa<br/>Palace Hotel</span><div className="location-context"><Img src={images.facade} alt="Hotel no contexto urbano próximo à lagoa"/></div><div className="lake"><Img src={images.lake} alt="Lagoa próxima ao Diamante Rosa Palace Hotel"/></div></div></section>

  <section className="final-cta" id="contato"><div className="cta-facet"/><Eyebrow n="09">SUA PRÓXIMA HISTÓRIA</Eyebrow><h2>Sua próxima estadia pode começar aqui.</h2><p>Diamante Rosa Palace Hotel<br/>Coromandel — Minas Gerais</p><div className="actions"><a href={hotel.whatsapp} className="button button--coral">Falar com a recepção <span>↗</span></a><a href="#localizacao" className="button button--line">Ver localização</a></div></section>
  <footer><Logo light/><p>Hospitalidade que se percebe nos detalhes.</p><div><a href={`tel:+553438413608`}>{hotel.phone}</a><a href="https://instagram.com/diamanterosapalace">{hotel.instagram}</a></div><nav><a href="#acomodacoes">Acomodações</a><a href="#experiencia">Experiência</a><a href="#estrutura">Estrutura</a><a href="#localizacao">Localização</a></nav><small>© {new Date().getFullYear()} Diamante Rosa Palace Hotel · Coromandel — MG</small></footer>
</main>}
